# Transformer

# Embeddings:
# both_embeddings: glove_dir/glove.6B.100d.txt
# embeddings_type: "GloVe"
# word_vec_size: 100
# save_data: scan_data/save_data

# Data
# Corpus opts:
data:
    corpus_1:
        path_src: scan_data/src_train.txt
        path_tgt: scan_data/tgt_train.txt
    valid:
        path_src: scan_data/src_val.txt
        path_tgt: scan_data/tgt_val.txt

# Vocabulary files
src_vocab: scan_data/run/scan.vocab.src
tgt_vocab: scan_data/run/scan.vocab.tgt

# General opts
save_model: models/tran
save_checkpoint_steps: 1000
valid_steps: 1000
train_steps: 10000

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 1
gpu_ranks: [0]
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 8
max_generator_batches: 2
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 2000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]